### PR TITLE
Refactor Main

### PR DESCRIPTION
**Pull request by jllopes**
Hey,

Following issue #265, I've refactored the code to make the lint function and LintOptions data structure available for files other than the main.
To do this I also had to move functions they depended on to another file.
Tell me if you think something needs to be redone.

Epic Code Reviews

### CODE REVIEW

**Comment by lorenzo** [comment]
Do you mind if I push some comments directly to your branch?

**Comment by jllopes** [comment]
@lorenzo Of course not, go ahead!

**Comment by lorenzo** [comment]
@jllopes I did a bigger refactor, so that most of the Main file actually lives in the library

**Comment by lorenzo** [comment]
@jllopes may I now ask what your use case was? Maybe the custom additions you want to create are also useful for everyone else and can be added directly to hadolint?

**Comment by jllopes** [comment]
@lorenzo 
We want to support Hadolint on Codacy and for that we need a docker image that can read our config file and run the tool with what patterns we define on it.
I've just created a wrapper that parses that config file and then runs Hadolint programmatically based on the parsed configuration.
I don't know if it would be useful to add it directly to Hadolint, but the code will be on our public fork so you can check that out later and, if it makes sense to add it, I will create a PR

**Comment by lorenzo** [comment]
cool, looking forward to see that. Thanks for your contributions!

**Pull request merged**
