### PR TITLE
Add Codacy to integrations page

### PR DESCRIPTION
**Pull request by DReigada**
Thank you for the great tool!
I am adding Codacy to the integration page as an automated code review tool.
This way, more people can use hadolint analysis out of the box, for free.

### CODE REVIEW

**Comment by lorenzo** [comment]
Hi, thanks for the contribution. Currently the linter for the markdown syntax is reporting some errors so this cannot be merged.

Additionally, can you tone down the marketing text you are adding? I'm fine with adding a high level description of what codify can do, but in the scope of this repo, it should focus on hadolint and not on all other things it can do.

**Comment by DReigada** [comment]
Hi @lorenzo, thank you for the feedback, I will change the description according to it.

**Comment by DReigada** [comment]
Hi @lorenzo, I've just updated the description to be more focused on the hadolint integration

**Comment by lorenzo** [comment]
Thanks! Do you mind finding the line length issue the markdown linter is reporting in travis?

**Comment by DReigada** [comment]
Fixed! By the way Codacy now supports remark-lint and it would create automatic comments in the PR on the lines where issues are found

**Comment by lorenzo** [comment]
@DReigada that would be awesome to have! is there a way you can send a pull request to enable it?

**Comment by DReigada** [comment]
@lorenzo you just need to add hadolint to Codacy, it would be better if it is through your account so that post commits hooks are enabled

**Pull request merged**
