### PR TITLE
Adds `/bin/sh` as a valid shell for DL4006

### PR DESCRIPTION
**Pull request by sdwolfz**
### What I did
- Added `/bin/sh` and `sh` as valid shells that can be linted for `-o pipefail` in DL4006
- Fixed the regression test.
- Added a stack generated file to the gitignore.

### How I did it
I noticed that a Dockerfile with
```dockerfile
SHELL ["/bin/sh", "-o", "pipefail"]
RUN env | grep FOO
```
Was failing `DL4006`.

So I checked the linter code and `/bin/sh` and `sh` were not present in the list of valid shells. I added them there and fixed the tests.

### How to verify it

Run `hadolint` on the snippet above before and after the change. Or check the tests.

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks a lot for the contribution, but regular `sh` does not actually allow `pipefail` :(

If you are using `alpine`, please follow this suggestion instead https://github.com/hadolint/hadolint/issues/250#issuecomment-409891140

**Comment by sdwolfz** [comment]
Hmm, in that case are you ok with updating the message text to hint at either chaining the shell in case it's sh or disabling the check?

**Comment by lorenzo** [comment]
@sdwolfz sure, I'm ok with updating the text. Would you like to do that?

**Comment by sdwolfz** [comment]
Another idea would be to detect 'set -o pipefail' in the `RUN` itself before a pipe is used, but I don't have the knowledge to implement that right now.

**Comment by sdwolfz** [comment]
> @sdwolfz sure, I'm ok with updating the text. Would you like to do that?

Yes I'll get to it in a few hours.

**Comment by sdwolfz** [comment]
@lorenzo The message is updated, please take a look :pray:

**Comment by lorenzo** [comment]
Thanks!!

**Pull request merged**
