### PR TITLE
Refactor lint

### PR DESCRIPTION
**Pull request by SimonAlling**
### What I did

I refactored `lint`.

### How I did it

I read the transformation described in

```haskell
do
  a <- ma
  return (f a)
```

as "extracting [`a` from `ma`], applying [`f`] and wrapping the result again" – also known as `fmap`.

I also eta-reduced `lintDockerfile`. Can of course be undone if you prefer to be more explicit. Let me know what you think.

### How to verify it

I don't know; I never managed to run `stack install`.

```
$ stack --version
2.1.3.1 x86_64 hpack-0.33.0
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```

<details>
<summary>Error message</summary>

```
/nix/store/cg0k49h66nkdqx6ccwnqr0i4q0fnfznc-binutils-2.31.1/bin/ld.gold: error: cannot find -lgmp
/home/alling/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwplusBigNatWord_info: error: undefined reference to '__gmpn_add_1'
/home/alling/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwminusBigNatWord_info: error: undefined reference to '__gmpn_sub_1'

[...]

/home/alling/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_ior_n: error: undefined reference to '__gmpn_ior_n'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /home/alling/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin/ghc-8.6.5 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.4.0.1 /home/alling/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/alling/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/alling/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5
    Process exited with code: ExitFailure 1
```

</details>

### CODE REVIEW

**Comment by lorenzo** [comment]
Hi, thanks. What's the motivation behind this change?

**Comment by SimonAlling** [comment]
> Hi, thanks. What's the motivation behind this change?

Merely me thinking that

```haskell
fmap f ma
```

is more idiomatic and succinct than

```haskell
do
  a <- ma
  return (f a)
```

I'm not a Haskell expert, though. What's your opinion?

**Comment by lorenzo** [comment]
@SimonAlling both are ok. I often prefer the `do` form as a way to welcome newcomers to the language as they are often more comfortable with the imperative-like look of it.

**Comment by SimonAlling** [comment]
OK. I'll leave this PR to be merged or closed as you see fit. :slightly_smiling_face:

**Comment by lorenzo** [comment]
deciced to keep it as is, in order to reduce the entry barrier for others

**Pull request closed without merging**
