### PR TITLE
use travis homebrew addon

### PR DESCRIPTION
**Pull request by stephengroat**
### What I did

update travis.yml to use addons

### How to verify it

travis build

### CODE REVIEW

**Comment by zemanlx** [comment]
@stephengroat thanks for the contribution!

Do you think that you can force it run only for deploy, because `brew` is time-consuming to run (it takes 386 seconds) and after your change, we will run it for every build.

**Comment by zemanlx** [comment]
@stephengroat `v3.94` works fine, but if there is a way of using updated `v3.95` without `brew update` I would rather use that one.

**Comment by stephengroat** [comment]
travis updates it `osx` images every once in a while, so you'll get that update eventually, but otherwise, there's no other easy/clean way that i know of (since `upx` doesn't release an `osx` binary)

**Comment by lorenzo** [comment]
I think this makes sense as it is. thanks!

**Pull request merged**
