### PR TITLE
Release/1.17.6

### PR DESCRIPTION
**Pull request by zemanlx**

### CODE REVIEW

**Comment by zowoq** [comment]
Could this be published to Hackage please? Thanks!

**Comment by zemanlx** [comment]
@lorenzo Would you be so kind and add how to do this to https://github.com/hadolint/hadolint/blob/master/docs/RELEASE.md so I can do this next time without bothering you?

**Comment by lorenzo** [comment]
will do

**Comment by lorenzo** [comment]
Done!

**Comment by zowoq** [comment]
Thanks!

**Pull request merged**
