### PR TITLE
Use the language-docker parser package

### PR DESCRIPTION
**Pull request by lorenzo**
This removes the parser code from this repo and delegates the job to
an external package

### CODE REVIEW

**Comment by zemanlx** [comment]
@lorenzo can you try to build it in appveyor without cache?

```yaml
cache:
  # Cache GHC
#  - 'C:\Users\appveyor\AppData\Local\Programs\stack'
  # Cache cabal packages
#  - 'C:\Users\appveyor\AppData\Roaming\stack'
```
in `appveyor.yml`

**Comment by lorenzo** [comment]
@zemanlx let's see if that works

**Comment by zemanlx** [comment]
@lorenzo I saw it yesterday with some AppVeyor builds. Still, I haven't found what can cause the issue. What about  update to newer lts version? Looks like that some hashes are broken and update may fix it :pray:

**Comment by lorenzo** [comment]
I’ll try a few things when I get home

**Comment by lorenzo** [comment]
@zemanlx fixed

**Comment by zemanlx** [comment]
@lorenzo Great! Can you please drop two _test_ commits? Then, I think we are good to go.

**Comment by lorenzo** [comment]
I squashed the commits instead

**Pull request merged**
