### PR TITLE
Updated INTEGRATION.md with GitHub Actions

### PR DESCRIPTION
**Pull request by maxneuvians**
Add demonstration of how to integrate with GitHub Actions.

### CODE REVIEW

**Comment by lorenzo** [comment]
Thank for the contribution, would you please fix the listing error in the markdown file?

**Comment by maxneuvians** [comment]
Thanks for the comment! I fixed the markdown linting issues - sorry about that, GitHub should really notify people of CI fails on non-author PRs. It seems that there is an issue with the Haskell linter:

```
./src/Hadolint/Rules.hs:448:5: Suggestion: Move guards forward
Found:
  [arg | cmd <- dropTarget <$> Shell.findCommands args,
   arg <- Shell.getArgsNoFlags cmd,
   Shell.cmdHasArgs "apt-get" ["install"] cmd, arg /= "install"]
Perhaps:
  [arg | cmd <- dropTarget <$> Shell.findCommands args,
   Shell.cmdHasArgs "apt-get" ["install"] cmd,
   arg <- Shell.getArgsNoFlags cmd, arg /= "install"]
./src/Hadolint/Rules.hs:513:5: Suggestion: Move guards forward
Found:
  [arg | cmd <- dropTarget <$> Shell.findCommands args,
   arg <- Shell.getArgsNoFlags cmd,
   Shell.cmdHasArgs "apk" ["add"] cmd, arg /= "add"]
Perhaps:
  [arg | cmd <- dropTarget <$> Shell.findCommands args,
   Shell.cmdHasArgs "apk" ["add"] cmd,
   arg <- Shell.getArgsNoFlags cmd, arg /= "add"]
```

If you want to fix that in master I can merge it in?

**Comment by lorenzo** [comment]
I'll just merge this, did not notice the listing error was related to Haskell and not the md. Thanks a lot for your contribution.

**Comment by maxneuvians** [comment]
Thank you @lorenzo - this is a really awesome tool!

**Pull request merged**
